Repository hmcts/snl-frontend, pull requests merged in 2018-12, with the labels that each got.

#261 [AKS] SL-1719 add helmetjs
  package.json
  server.ts
  yarn.lock
Labels: WIP, ns:snl-frontend-pr-261

#272 [AKS] Withdraw hearing test
  e2e/e2e-url.js
  e2e/models/delete-listing-request-body.ts
  e2e/pages/dialog.po.ts
  e2e/pages/search-listing-request.po.ts
  e2e/pages/top-menu.po.ts
  e2e/pages/transaction-dialog.po.ts
  e2e/pages/view-hearing.po.ts
  e2e/protractor.conf.js
  e2e/specs/withdraw-hearing.e2e-spec.ts
  e2e/utils/api.ts
  e2e/utils/element-helper.ts
  src/app/hearing/components/view-hearing/view-hearing.component.html
Labels: ns:snl-frontend-pr-272

#271 [AKS] SL-1855: add history tab to hearing details screen
  src/app/core/core.module.ts
  src/app/core/pipes/moment-format.pipe.ts
  src/app/features/activityLog/activity-log.module.ts
  src/app/features/activityLog/components/activities-log.component.html
  src/app/features/activityLog/components/activities-log.component.scss
  src/app/features/activityLog/components/activities-log.component.spec.ts
  src/app/features/activityLog/components/activities-log.component.ts
  src/app/features/activityLog/models/activity-log.model.ts
  src/app/features/activityLog/services/activity-log.service.spec.ts
  src/app/features/activityLog/services/activity-log.service.ts
  src/app/hearing/components/view-hearing/view-hearing.component.html
  src/app/hearing/components/view-hearing/view-hearing.component.spec.ts
  src/app/hearing/components/view-hearing/view-hearing.component.ts
  src/app/hearing/hearing.module.ts
  src/app/hearing/services/hearing.service.spec.ts
  src/app/hearing/services/possible-hearing-actions.service.spec.ts
Labels: ns:snl-frontend-pr-271

#274 [AKS] SL-1794 additional action when changing joh for a session with multi part hearing via planner
  src/app/common/ng-fullcalendar/models/calendar-mouse-event.model.ts
  src/app/common/ng-fullcalendar/models/event-drop.model.ts
  src/app/common/ng-fullcalendar/models/updateEventModel.ts
  src/app/common/ng-fullcalendar/ng-full-calendar.component.ts
  src/app/core/callendar/components/calendar.component.spec.ts
  src/app/core/callendar/components/calendar.component.ts
  src/app/core/callendar/containers/calendar-container.component.ts
  src/app/core/callendar/transformers/data-with-simple-resource-transformer.ts
  src/app/core/callendar/transformers/default-data-transformer.spec.ts
  src/app/core/callendar/transformers/default-data-transformer.ts
  src/app/core/callendar/transformers/icalendar-transformer.ts
  src/app/planner/components/judge-planner/judge-planner.component.spec.ts
  src/app/planner/components/judge-planner/judge-planner.component.ts
  src/app/planner/components/room-planner/room-planner.component.ts
  src/app/planner/containers/planner.component.html
  src/app/planner/containers/planner.component.spec.ts
  src/app/planner/containers/planner.component.ts
  src/app/planner/services/summary-message.service.spec.ts
  src/app/planner/services/summary-message.service.ts
  src/app/planner/types/calendar-event-session-view-model.type.ts
  src/app/sessions/actions/session.action.ts
  src/app/sessions/effects/session.effects.ts
  src/app/sessions/models/drag-and-drop-session-request.model.ts
  src/app/sessions/models/drag-and-drop-session.model.ts
  src/app/sessions/models/session.viewmodel.ts
  src/app/sessions/services/sessions-creation.service.ts
  src/app/sessions/services/sessions-service.ts
Labels: ns:snl-frontend-pr-274

#282 [AKS] Tide up + fix unit test
  src/app/planner/components/judge-planner/judge-planner.component.spec.ts
  src/app/sessions/containers/sessions-search/sessions-search.component.ts
Labels: ns:snl-frontend-pr-282

#277 [AKS] Feature/sl 1853/start time for listing
  Jenkinsfile_CNP
  src/app/core/callendar/components/calendar.component.ts
  src/app/core/pipes/moment-format.pipe.spec.ts
  src/app/core/validators/time-format.validator.ts
  src/app/hearing/components/amend-scheduled-listing/amend-scheduled-listing.component.html
  src/app/hearing/components/amend-scheduled-listing/amend-scheduled-listing.component.spec.ts
  src/app/hearing/components/amend-scheduled-listing/amend-scheduled-listing.component.ts
  src/app/hearing/components/view-hearing/view-hearing.component.html
  src/app/hearing/components/view-hearing/view-hearing.component.scss
  src/app/hearing/components/view-hearing/view-hearing.component.spec.ts
  src/app/hearing/components/view-hearing/view-hearing.component.ts
  src/app/hearing/hearing.module.ts
  src/app/hearing/models/amend-scheduled-listing.ts
  src/app/hearing/models/hearing.ts
  src/app/hearing/services/hearing.service.spec.ts
  src/app/hearing/services/hearing.service.ts
  src/app/planner/components/judge-planner/judge-planner.component.spec.ts
  src/app/sessions/containers/sessions-listings-search/sessions-listings-search.component.ts
  src/styles.css
Labels: ns:snl-frontend-pr-277

#275 [AKS] Feature/sl 2043 automated rollback frontend changes
  e2e/e2e-url.js
  e2e/pages/view-hearing.po.ts
  src/app/features/transactions/actions/transaction.action.ts
  src/app/features/transactions/components/transaction-dialog/transaction-dialog.component.spec.ts
  src/app/features/transactions/components/transaction-dialog/transaction-dialog.component.ts
  src/app/features/transactions/effects/transaction.effects.spec.ts
  src/app/features/transactions/effects/transaction.effects.ts
  src/app/sessions/containers/sessions-create/sessions-create-component.spec.ts
Labels: ns:snl-frontend-pr-275

#281 [AKS] Bugfix/sl 2062/notes display incosistency
  src/app/hearing-part/components/hearings-table/hearings-table.component.spec.ts
  src/app/hearing-part/components/hearings-table/hearings-table.component.ts
  src/app/hearing-part/components/listing-note-list/listing-note-list.component.ts
  src/app/notes/components/notes-list-dialog/notes-list-dialog.component.spec.ts
  src/app/notes/components/notes-list-dialog/notes-list-dialog.component.ts
  src/app/notes/models/note.model.ts
  src/app/notes/models/note.viewmodel.ts
Labels: ns:snl-frontend-pr-281

#279 [AKS] SnL-2120: custom validators
  src/app/core/validators/date-format.validator.spec.ts
  src/app/core/validators/date-format.validator.ts
  src/app/core/validators/time-format.validator.spec.ts
  src/app/sessions/components/sessions-create-form/sessions-create-form.component.html
  src/app/sessions/components/sessions-create-form/sessions-create-form.component.ts
  src/app/utils/date-utils.spec.ts
  src/app/utils/date-utils.ts
  src/public/config.json
Labels: ns:snl-frontend-pr-279

#285 [AKS] Feature/sl 2063/search listing filters
  karma.conf.js
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/services/i-storage.interface.ts
  src/app/core/services/in-memory-storage.service.spec.ts
  src/app/core/services/in-memory-storage.service.ts
  src/app/hearing-part/components/hearing-search-table/hearing-search-table.component.html
  src/app/hearing-part/components/hearing-search-table/hearing-search-table.component.ts
  src/app/hearing-part/components/hearings-filter/hearings-filter.component.ts
  src/app/hearing-part/containers/hearings-search/hearings-search.component.html
  src/app/hearing-part/containers/hearings-search/hearings-search.component.spec.ts
  src/app/hearing-part/containers/hearings-search/hearings-search.component.ts
Labels: ns:snl-frontend-pr-285

#284 [AKS] Feature/sl 1878/reason for adjournment
  src/app/features/activityLog/components/activities-log.component.html
  src/app/features/notification/components/dialog-with-actions/dialog-with-actions.component.ts
  src/app/hearing/components/adjourn-hearing-dialog/adjourn-hearing.dialog.component.html
  src/app/hearing/components/adjourn-hearing-dialog/adjourn-hearing.dialog.component.ts
  src/app/hearing/components/adjourn-hearing-dialog/adjourn-hearing.dialog.scss
  src/app/hearing/hearing.module.ts
  src/app/hearing/models/hearing.ts
  src/app/hearing/models/possible-action-config.ts
  src/app/hearing/services/hearing.service.spec.ts
  src/app/hearing/services/hearing.service.ts
  src/app/hearing/services/possible-hearing-actions.service.spec.ts
  src/app/hearing/services/possible-hearing-actions.service.ts
  src/app/planner/components/judge-planner/judge-planner.component.spec.ts
Labels: ns:snl-frontend-pr-284

#287 [AKS] SL-2170: Fixed logic, unit tests to do
  src/app/sessions/containers/sessions-listings-search/sessions-listings-search.component.spec.ts
  src/app/sessions/containers/sessions-listings-search/sessions-listings-search.component.ts
  src/app/utils/moment-utils.spec.ts
  src/app/utils/moment-utils.ts
  src/public/config.json
Labels: ns:snl-frontend-pr-287

#289 [AKS] SL-2177 Restrictions on changes to a session which contains listings
  src/app/common/ng-fullcalendar/models/event-drag.model.ts
  src/app/common/ng-fullcalendar/ng-full-calendar.component.ts
  src/app/core/callendar/components/calendar.component.html
  src/app/core/callendar/components/calendar.component.ts
  src/app/core/callendar/containers/calendar-container.component.ts
  src/app/core/callendar/transformers/default-data-transformer.spec.ts
  src/app/core/callendar/transformers/default-data-transformer.ts
  src/app/core/validators/session-amend.validators.spec.ts
  src/app/core/validators/session-amend.validators.ts
  src/app/hearing-part/actions/hearing.action.spec.ts
  src/app/hearing-part/components/hearings-table/hearings-table.component.spec.ts
  src/app/hearing-part/components/hearings-table/hearings-table.component.ts
  src/app/hearing-part/containers/hearings-search/hearings-search.component.spec.ts
  src/app/hearing-part/containers/hearings-search/hearings-search.component.ts
  src/app/hearing-part/models/hearing-part-response.ts
  src/app/hearing-part/models/hearing-part.ts
  src/app/hearing-part/models/hearing-part.viewmodel.ts
  src/app/hearing-part/reducers/hearing-part.reducer.spec.ts
  src/app/hearing-part/reducers/index.ts
  src/app/planner/components/judge-planner/judge-planner.component.spec.ts
  src/app/planner/containers/planner.component.spec.ts
  src/app/planner/containers/planner.component.ts
  src/app/planner/services/summary-message.service.spec.ts
  src/app/planner/services/validator.spec.ts
  src/app/planner/services/validator.ts
  src/app/planner/types/calendar-event-session-view-model.type.ts
  src/app/planner/validators/session-modification.validator.spec.ts
  src/app/planner/validators/session-modification.validator.ts
  src/app/sessions/components/sessions-amend-form/sessions-amend-form.component.html
  src/app/sessions/components/sessions-amend-form/sessions-amend-form.component.scss
  src/app/sessions/components/sessions-amend-form/sessions-amend-form.component.spec.ts
  src/app/sessions/components/sessions-amend-form/sessions-amend-form.component.ts
  src/app/sessions/containers/sessions-search/sessions-search.component.ts
  src/app/sessions/mappers/amend-session-form-session-amend.ts
  src/app/sessions/models/ammend/session-ammend-form.model.ts
  src/app/sessions/models/ammend/session-ammend.model.ts
  src/app/sessions/models/session-amend.response.ts
  src/app/sessions/models/session.viewmodel.ts
  src/app/sessions/services/sessions-service.spec.ts
Labels: ns:snl-frontend-pr-289
